services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/code/app

    networks:
      - chatbot-network
    
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: chatbot-db
    command: 
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci

    env_file:
      - .env

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    
    volumes:
      - mysql-data:/var/lib/mysql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - chatbot-network

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  chatbot-network:

volumes:
  mysql-data:
